### ISSUE TITLE
Images on common file pages not in responses

### ISSUE THREAD

**Issue by jdlrobson** [jdlrobson/weekipedia#125]
http://localhost:8142/api/page/en.commons/File%3ATempodrom%2C%20Berl%C3%ADn%2C%20Alemania%2C%202016-04-22%2C%20DD%2001-03%20HDR.JPG

**Comment by berndsi** [comment]
That's a Parsoid bug https://phabricator.wikimedia.org/T148118.

I'm sad to say the app works around this by using the mobileview response for File: pages until Parsoid fixes the issue.
Maybe we could just have MCS do the switch instead. Then MCS clients wouldn't need to keep working around this issue.
