### ISSUE TITLE
Redirects are swallowed

### ISSUE THREAD

**Issue by jdlrobson** [jdlrobson/weekipedia#134]
https://en.wikivoyage.org/api/rest_v1/page/mobile-sections/Erhai%20Lake redirects to https://en.wikivoyage.org/api/rest_v1/page/mobile-sections/Dali

but http://localhost:8142/api/voyager/page/en.wikivoyage/Erhai%20Lake doesn't.

**Comment by berndsi** [comment]
Redirects happen in RESTBase, not in MCS. In MCS redirects are explicitly turned off using a query parameter `redirect: false`.

**Comment by jdlrobson** [comment]
Fixed in above but has caused #135
